package com.senseicoder.quickcart.core.global.enums

enum class DialogType{
    LOGOUT,DEL_ADDRESS,DEL_PRODUCT,SAVE_ADDRESS,DEL_FAV,GUEST_MODE,SIGN_UP_FIRST_NAME,SIGN_UP_LAST_NAME,SIGN_UP_EMAIL,PERMISSION_DENIED_GUEST_MODE
}